# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English")],
                default="de",
                max_length=2,
                verbose_name="Site language",
            ),
        )
    ]
