FROM python:3.6.3-alpine3.6
ENV PYTHONBUFFERED 1
ARG VERBOSE

# Add new user to run the whole thing as non-root
RUN addgroup -S app
RUN adduser -G app -u 2000 -h /app -D app

COPY docker/local/start.sh /start.sh
RUN chmod +x /start.sh

# Copy Pipfile and install system-wide
# We're installing system-wide, because we currently have problems
# correctly using the entrypoint.sh, while activating the virtual environment
COPY Pipfile Pipfile.lock /app/
WORKDIR /app

# Install build dependencies for PostgreSQL. While we're at it, also install
# pipenv and all python requirements. Then remove unneeded build dependencies.
RUN apk update \
    && apk add --no-cache --virtual .build-deps \
       gcc \
       musl-dev \
       zlib-dev \
       jpeg-dev \
       libxslt-dev \
       libxml2-dev \
       git \
    && apk add --no-cache postgresql postgresql-dev jpeg \
    && pip install pipenv \
    && LIBRARY_PATH=/lib:/usr/lib /bin/sh -c "pipenv install --dev --system $VERBOSE" \
    && apk del .build-deps

# Change to user and copy code
COPY . /app
USER app

# Let Django collect all staticfiles
RUN python /app/manage.py collectstatic --noinput

ENTRYPOINT ["/app/docker/local/entrypoint.sh"]
