FROM node:8.9-alpine

RUN deluser --remove-home node \
    && addgroup -S app \
    && adduser -G app -u 1000 -h /app -D app

USER app

COPY --chown=app:app . ./app/
WORKDIR /app

RUN yarn install --dev \
    && yarn build
