# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-13 08:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shifts", "0005_auto_20160613_1203")]

    operations = [
        migrations.AlterModelOptions(
            name="shift", options={"ordering": ["-shift_finished"]}
        )
    ]
