# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_auto_20170513_1059'),
    ]

    operations = [
        migrations.RenameField('Shift', 'shift_started', 'started'),
        migrations.RenameField('Shift', 'shift_finished', 'finished'),
        migrations.RenameField('Shift', 'shift_duration', 'duration'),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-finished']},
        )
    ]
