# Generated by Django 2.0 on 2017-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20171022_1456")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        )
    ]
