from django.conf.urls import url
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import RedirectView

favicon_urlpatters = [
    # url(r'^android-chrome-36x36.png',
    #     RedirectView.as_view(
    #         url=staticfiles_storage.url(
    #             'common/favicons/android-chrome-36x36.png'),
    #         permanent=False)),
    url(
        r"^android-chrome-48x48.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/android-chrome-48x48.png"),
            permanent=False,
        ),
    ),
    url(
        r"^android-chrome-72x72.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/android-chrome-72x72.png"),
            permanent=False,
        ),
    ),
    url(
        r"^android-chrome-96x96.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/android-chrome-96x96.png"),
            permanent=False,
        ),
    ),
    url(
        r"^android-chrome-144x144.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/android-chrome-144x144.png"),
            permanent=False,
        ),
    ),
    url(
        r"^android-chrome-192x192.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/android-chrome-192x192.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-57x57.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-57x57.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-60x60.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-60x60.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-72x72.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-72x72.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-76x76.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-76x76.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-114x114.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-114x114.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-120x120.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-120x120.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-144x144.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-144x144.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-152x152.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-152x152.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-180x180.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon-180x180.png"),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon-precomposed.png",
        RedirectView.as_view(
            url=staticfiles_storage.url(
                "common/favicons/apple-touch-icon-precomposed.png"
            ),
            permanent=False,
        ),
    ),
    url(
        r"^apple-touch-icon.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/apple-touch-icon.png"),
            permanent=False,
        ),
    ),
    url(
        r"^favicon-16x16.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/favicon-16x16.png"),
            permanent=False,
        ),
    ),
    url(
        r"^favicon-32x32.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/favicon-32x32.png"),
            permanent=False,
        ),
    ),
    url(
        r"^favicon-96x96.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/favicon-96x96.png"),
            permanent=False,
        ),
    ),
    url(
        r"^favicon.ico$",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/favicon.ico"), permanent=False
        ),
    ),
    url(
        r"^mstile-70x70.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/mstile-70x70.png"),
            permanent=False,
        ),
    ),
    url(
        r"^mstile-144x144.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/mstile-144x144.png"),
            permanent=False,
        ),
    ),
    url(
        r"^mstile-150x150.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/mstile-150x150.png"),
            permanent=False,
        ),
    ),
    url(
        r"^mstile-310x150.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/mstile-310x150.png"),
            permanent=False,
        ),
    ),
    url(
        r"^mstile-310x310.png",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/mstile-310x310.png"),
            permanent=False,
        ),
    ),
    url(
        r"^safari-pinned-tab.svg",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/safari-pinned-tab.svg"),
            permanent=False,
        ),
    ),
    url(
        r"^browserconfig.xml",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/browserconfig.xml"),
            permanent=False,
        ),
    ),
    url(
        r"^manifest.json",
        RedirectView.as_view(
            url=staticfiles_storage.url("common/favicons/manifest.json"),
            permanent=False,
        ),
    ),
]
